version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: report_db
    environment:
      POSTGRES_USER: Guzman
      POSTGRES_PASSWORD: rootGuzman
      POSTGRES_DB: reportes_db
    ports:
      - "5432:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d

  web:
    build: .
    container_name: report_web
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://reportes_user:24371512%40@db:5432/reportes_db
    depends_on:
      - db
